// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Com1Label;
extern lv_obj_t * ui_Com1Res;
extern lv_obj_t * ui_Com1Stdby;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_MyFont);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
