// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Com1Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Com1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Com1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Com1Label, -120);
    lv_obj_set_y(ui_Com1Label, -91);
    lv_obj_set_align(ui_Com1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Com1Label, "COM1:");
    lv_obj_set_style_text_font(ui_Com1Label, &ui_font_MyFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Com1Res = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Com1Res, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Com1Res, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Com1Res, -49);
    lv_obj_set_y(ui_Com1Res, -91);
    lv_obj_set_align(ui_Com1Res, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Com1Res, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Com1Res, "131.200");
    lv_obj_set_style_text_font(ui_Com1Res, &ui_font_MyFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Com1Stdby = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Com1Stdby, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Com1Stdby, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Com1Stdby, 80);
    lv_obj_set_y(ui_Com1Stdby, -89);
    lv_obj_set_align(ui_Com1Stdby, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Com1Stdby, "120.000");
    lv_obj_set_style_text_font(ui_Com1Stdby, &ui_font_MyFont, LV_PART_MAIN | LV_STATE_DEFAULT);

}
